stages:
  data_ingestion:
    cmd: python src/mlproject/pipeline/stage_01_data_ingestion.py
    deps:
    - src/mlproject/pipeline/stage_01_data_ingestion.py
    outs:
    - artifacts/data_ingestion

  data_validation:
    cmd: python src/mlproject/pipeline/stage_02_data_validation.py
    deps:
    - artifacts/data_ingestion
    - src/mlproject/pipeline/stage_02_data_validation.py
    outs:
    - artifacts/data_validation
  data_transformation:
    cmd: python src/mlproject/pipeline/stage_03_data_transformation.py
    deps:
    - artifacts/data_ingestion
    - src/mlproject/pipeline/stage_03_data_transformation.py
    outs:
    - artifacts/data_transformation
  model_trainer:
    cmd: python src/mlproject/pipeline/stage_04_model_trainer.py
    deps:
    - artifacts/data_validation
    - src/mlproject/pipeline/stage_04_model_trainer.py
    params:
    - ElasticNet.alpha
    - ElasticNet.l1_ratio
    outs:
    - artifacts/model_trainer
  model_evaluation:
    cmd: python src/mlproject/pipeline/stage_05_model_evaluation.py
    deps:
    - artifacts/data_transformation
    - artifacts/model_trainer
    - src/mlproject/pipeline/stage_05_model_evaluation.py
    params:
    - ElasticNet.alpha
    - ElasticNet.l1_ratio
    outs:
    - artifacts/model_evaluation
