stages:
  data_ingestion:
    cmd: python src/mlproject/pipeline/stage_01_data_ingestion.py
    deps:
    - src/mlproject/pipeline/stage_01_data_ingestion.py
    outs:
    - artifacts/data_ingestion

  data_validation:
    cmd: python src/mlproject/pipeline/stage_02_data_validation.py
    deps:
    - artifacts/data_ingestion
    - src/mlproject/pipeline/stage_02_data_validation.py
    outs:
    - artifacts/data_validation
